version: '3'

services: 
    php: 
        build:
            context: ./php
        links:
            - "mysql"
        ports:
            - "8001:80"
    mysql: 
        build:
            context: ./
