version: '3'

services: 
    nginx:
        build: ./build/nginx
        container_name: nginx
        tty: true
        links: 
            - php
        ports: 
            - "80:80"
        volumes:
            - "/etc/passwd:/etc/passwd"
            - "/etc/group:/etc/group"
            - "./etc/nginx/conf.d:/etc/nginx/conf.d:ro"
            - "/www/nginx/html:/usr/share/nginx/html:ro"
            - "/www:/www"
    php: 
        build: ./build/php
        container_name: php
        links: 
            - "mysql"
        volumes: 
            - "/etc/passwd:/etc/passwd"
            - "/etc/group:/etc/group"
            - "./etc/php.ini:/etc/php.ini"
            - "/www:/www:ro"
    mysql:
        build: ./build/mysql
        container_name: mysql
        tty: true
        env_file:
            - mysql.env
        ports:
            - "3306:3306"
        volumes:
            - "/etc/passwd:/etc/passwd"
            - "/etc/group:/etc/group"
            - "./data/mysql:/var/lib/mysql"
            - "./etc/mysql/my.cnf:/etc/mysql/my.cnf"
            - "./etc/mysql/conf.d:/etc/mysql/conf.d"
