version: '3'

services: 
    nginx:
        build: 
            context: ./build/nginx
        container_name: nginx
        tty: true
        links: 
            - php
        ports: 
            - "80:80"
        volumes:
            - "./etc/nginx/conf.d:/etc/nginx/conf.d:ro"
            - "/www/nginx/html:/usr/share/nginx/html:ro"
            - "/www:/www"
    php: 
        build: 
            context: ./build/php
            args:
                USER_ID: 1000
                GROUP_ID: 1000
        container_name: php
        links: 
            - "mysql"
        volumes: 
            - "./etc/php:/usr/local/etc/php"
            - "./etc/php/conf.d:/usr/local/etc/php/conf.d"
            - "/www:/www"
        ports:
            - "9000:9000"
    mysql:
        build: 
            context: ./build/mysql
            args:
                HOST_USER_ID: 997
                HOST_GROUP_ID: 993
                MYSQL_ROOT_PASSWORD: 123456
                MYSQL_DATABASE: test
                MYSQL_USER: mattkay
                MYSQL_PASSWORD: 123456
        container_name: mysql
        tty: true
        ports:
            - "3306:3306"
        volumes:
            - "./data/mysql:/var/lib/mysql"
            - "./etc/mysql/my.cnf:/etc/mysql/my.cnf"
            - "./etc/mysql/conf.d:/etc/mysql/conf.d"
    redis: 
        build:
            context: ./build/redis
            args: 
                HOST_USER_ID: 1001
                HOST_GROUP_ID: 1001
        container_name: redis
        tty: true
        ports:
            - "6379:6379"
        volumes:
            - "./etc/redis:/usr/local/etc/redis"
            - "./data/redis:/data"
        command: 
            - redis-server
            - /usr/local/etc/redis/redis.conf
