version: '3'

services: 
    php: 
        build: ./build/php
        container_name: php
        link: 
            - "mysql"
        ports:
            - "80:80"
        volumes: 
            - ./etc/php.ini:/etc/php.ini
    mysql:
        build: ./build/mysql
        container_name: mysql
        ports:
            - "3306:3306"
        volumes:
            - ./data/db/mysql:/var/lib/mysql
