version: '3'

services: 
    php: 
        build: ./php
        container_name: php
        link: 
            - "mysql"
        ports:
            - "80:80"
        volumes: 
            - /www/docker/php:/www/docker/php
    mysql:
        build: ./mysql
        container_name: mysql
        ports:
            - "3306:3306"
        volumes:
            - /www/docker/mysql:/www/docker/mysql
